### PR TITLE
Provide a flag to control generation of the invocation comment

### LINKED ISSUE #104: Allow generation of the “Generated by this command” comment to be disabled
*Requested feature*
A way to disable generation of the “Generated by this command” comment.

*Why the feature is needed*
The comment has already been fixed to drop the path to `mockgen`, since that isn’t necessarily consistent. The same applies to paths provided as arguments; see https://github.com/kubernetes/kubernetes/pull/120969 for one such instance (the `copyright_file` arguments point to files in temporary directories).

*(Optional) Proposed solution*
I am about to submit a PR adding an option to take care of this by adding a command-line option to disable it.
Another possibility would be to remove paths from file names provided as arguments, perhaps only if they are absolte, but that may not be generally desirable.

### PR DESCRIPTION
**Pull request by skitt**
The invocation comment stores the complete details of all provided arguments, which may include paths to files. These aren't always consistent, which results in unwanted changes in the generated files (especially for CI checking for unexpected changes...).

Since the invocation isn't always useful, provide a flag to control whether the comment is generated. To preserve current behaviour this defaults to true (enabled).

Fixes #104.

### CODE REVIEW

**Review by marten-seemann — APPROVED** [review]

**Comment by ewhauser** [comment]
@skitt - Can you sign the CLA so that this gets merged? Thank you!

**Review by tchung1118 — APPROVED** [review]
LGTM. Will be merged once author signs CLA.

**Comment by skitt** [comment]
> @skitt - Can you sign the CLA so that this gets merged? Thank you!

I’m just waiting for our legal department to check it.

**Comment by sodul** [comment]
@skitt any progress on the CLA? We are staying at v0.2.0 until there is a new release with this fix.

**Comment by skitt** [comment]
> @skitt any progress on the CLA? We are staying at v0.2.0 until there is a new release with this fix.

It’s still pending, sorry...

**Review by JacobOaks — APPROVED** [review]

**Comment by sodul** [comment]
@JacobOaks I've created an alternate PR against the latest main (no conflicts) and have signed the CLA. This should allow for mockgen to be released with this issue fixed for good.

**Comment by JacobOaks** [comment]
Hey @skitt, closing as superceded by #153. Thanks!

**Comment by skitt** [comment]
That’s fine @JacobOaks, thanks @sodul for proposing an alternate PR!

**Pull request closed without merging**
